name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake flex bison build-essential

    - name: Configure and Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run Tests
      run: bash tests/run_tests.sh